# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

#r_check_args: "--run-dontrun"

r_binary_packages:
  - stringi
  - magrittr
  - curl
  - jsonlite
  - Rcpp
  - RcppEigen
  - openssl
  - utf8
  - gss
  - haven
  - minqa
  - mvtnorm
  - nloptr
  - SparseM
  - httpuv
  - markdown
  - pander
  - lme4
  - git2r

r_packages:
  - rlang
  - bindrcpp
  - purrr
  - tidyr
  - dplyr
  - readr
  - covr

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
