codecov:
  token: f86f6f51-9567-4692-b87f-4ac80db66e7b
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches: null
        informational: true

    patch:
      default:
        target: auto
        branches: 1%
        informational: true

    changes:
      default:
        branches: null
        threshold: 1%
        informational: true

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
